### PR TITLE
Fixed grid item support

### PR DESCRIPTION
**Pull request by eduardojunio**
This PR adds support to fixed elements inside the grid. Those elements aren't affected by other elements rearrangement.

The O letter has a fixed property set
**In this example the O letter has the fixed property**

### CODE REVIEW

**Comment by eduardojunio** [comment]
@ollija could you please review this PR and give me some feedback?

**Comment by danbtl** [comment]
👍  Working well! Exactly what I needed in my project.

**Comment by eduardojunio** [comment]
@danbtl glad to hear that 😄

**Comment by karims10** [comment]
Awesome, many thanks @eduardojunio 
Hope this'll be merged soon

**Comment by reidkersey** [comment]
Merged this into a fork. Works wonders. Thanks @eduardojunio. 

Forked code: https://github.com/reidkersey/react-native-sortable-grid

**Comment by eduardojunio** [comment]
Closing this PR since it has been 4 years already and the library maintainer didn't left any feedback.

**Pull request closed without merging**
